// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=08426866cf37a0cf3ec71724a42f8f6d01e515c4d00a949be7d481fb3ab67a15
package simd

import "math"

func f32_to_bits(f float32) uint32 {
	return math.Float32bits(f)
}

func C2_quantize_row_q8_k(x []float32, y []byte, cols int) {
	var v8 int
	var v9 int
	var v10 int
	var v11 int
	var v14 int
	var v23 float32
	var v107 int
	var v129 int
	v7 := y[:]
	v8 = 0
	for v8 < (cols / 0x100) {
		v17 := v8 * 0x100
		v21 := v8 * 0x124
		v23 = 0
		for v9 = 0; v9 < 0x100; v9++ {
			v30 := x[v17+v9]
			v37 := func() float32 {
				if v30 < float32(0) {
					return -v30
				}
				return v30
			}()
			if v37 > v23 {
				v23 = v37
			}
		}
		if v23 == float32(0) {
			v7[v21] = 0
			v7[v21+1] = 0
			v7[v21+2] = 0
			v7[v21+3] = 0
			clear(v7[int(v21+4):])
			clear(v7[int(v21+0x104):])
			v14 = v8 + 1
			v8 = v14
			continue
		}
		v69 := f32_to_bits(v23 / float32(127))
		v71 := v69 & 0xff
		v7[v21] = byte(v71)
		v78 := uint32(v69>>8) & 0xff
		v7[v21+1] = byte(v78)
		v85 := uint32(v69>>16) & 0xff
		v7[v21+2] = byte(v85)
		v92 := uint32(v69>>24) & 0xff
		v7[v21+3] = byte(v92)
		for v9 = 0; v9 < 0x100; v9++ {
			v106 := x[v17+v9] * (float32(127) / v23)
			v114 := func() float32 {
				if v106 >= float32(0) {
					return (v106 + float32(0.5))
				}
				return (v106 - float32(0.5))
			}()
			v107 = int(v114)
			if v107 > 127 {
				v107 = 127
			}
			if v107 < -127 {
				v107 = -127
			}
			v7[v21+v9+4] = byte(int8(v107))
		}
		for v10 = 0; v10 < 16; v10++ {
			v129 = 0
			v11 = 0
			for v11 < 16 {
				v129 += int(int8(v7[int(v21+((4+(v10*16))+v11))]))
				v11++
			}
			v146 := v129 & 255
			v151 := 0x104 + (v10 * 2)
			v7[v21+v151] = byte(v146)
			v158 := (v129 >> 8) & 255
			v7[v21+v151+1] = byte(v158)
		}
		v14 = v8 + 1
		v8 = v14
	}
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const (
	F32_to_bits_IRCost          = uint64(6)
	C2_quantize_row_q8_k_IRCost = uint64(190)
)
