//go:build goexperiment.simd && amd64

// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=5edc753d35f64010081305ab68ca6c97b39c4d77877016a73c8bf4663a80ea16
package simd

import "simd/archsimd"

func C2_tensor_dot_q4_k(weight []byte, x []float32, cols int) float32 {
	var v10 int
	var v11 int
	var v12 int
	var v13 int
	var v19 archsimd.Float32x8
	v4 := weight[:]
	v7 := cols / 0x100
	_ = float32(0)
	if archsimd.X86.AVX2() {
		v18 := archsimd.BroadcastUint8x16(byte(15))
		v19 = archsimd.BroadcastFloat32x8(float32(0))
		for v10 = 0; v10 < v7; v10++ {
			v26 := v10 * 144
			v40 := fp16_to_fp32(uint16(v4[v26]) | uint16(uint16(v4[(v26+1)])<<8))
			v53 := fp16_to_fp32(uint16(v4[(v26+2)]) | uint16(uint16(v4[(v26+3)])<<8))
			v57 := v26 + 4
			var v66 [8]byte
			var v67 [8]byte
			v11 = 0
			for v11 < 4 {
				v72 := v4[v57+v11]
				v75 := v72 & 63
				v66[v11] = v75
				v77 := v11 + 4
				v78 := v4[v57+v77]
				v81 := v78 & 63
				v67[v11] = v81
				v84 := v4[v57+v11+8]
				v87 := v84 & 15
				v66[v77] = v87 | byte(uint32((uint32(v72)>>6)<<4))
				v67[v77] = byte((uint32(v84) >> 4) | uint32((uint32(v78)>>6)<<4))
				v11++
			}
			v12 = 0
			for v12 < 4 {
				v120 := 2 * v12
				v142 := (v10 * 0x100) + (v12 * 64)
				v147 := (v26 + 16) + (v12 * 32)
				v151 := archsimd.LoadUint8x16(v4[v147:][:16])
				v158 := archsimd.LoadUint8x16(v4[int(v147+16):][:16])
				v160 := v151.And(v18)
				v162 := v158.And(v18)
				v184 := archsimd.LoadFloat32x8(x[v142:][:8])
				v190 := archsimd.LoadFloat32x8(x[int(v142+8):][:8])
				v196 := archsimd.LoadFloat32x8(x[int(v142+16):][:8])
				v202 := archsimd.LoadFloat32x8(x[int(v142+24):][:8])
				v204 := v160.ExtendLo8ToUint32().AsInt32x8().ConvertToFloat32().Mul(v184)
				v205 := v160.ConcatShiftBytesRight(v160, 8).ExtendLo8ToUint32().AsInt32x8().ConvertToFloat32().Mul(v190)
				v206 := v204.Add(v205)
				v207 := v162.ExtendLo8ToUint32().AsInt32x8().ConvertToFloat32().Mul(v196)
				v208 := v162.ConcatShiftBytesRight(v162, 8).ExtendLo8ToUint32().AsInt32x8().ConvertToFloat32().Mul(v202)
				v209 := v207.Add(v208)
				v212 := v184.Add(v190)
				v213 := v196.Add(v202)
				v217 := v212.Add(v213).Mul(archsimd.BroadcastFloat32x8(v53 * float32(v67[v120])))
				v218 := v206.Add(v209).Mul(archsimd.BroadcastFloat32x8(v40 * float32(v66[v120]))).Sub(v217)
				v19 = v19.Add(v218)
				v224 := v120 + 1
				v243 := v142 + 32
				v247 := v151.AsUint16x8().ShiftAllRight(4).AsUint8x16().And(v18)
				v251 := v158.AsUint16x8().ShiftAllRight(4).AsUint8x16().And(v18)
				v273 := archsimd.LoadFloat32x8(x[v243:][:8])
				v279 := archsimd.LoadFloat32x8(x[int(v243+8):][:8])
				v285 := archsimd.LoadFloat32x8(x[int(v243+16):][:8])
				v291 := archsimd.LoadFloat32x8(x[int(v243+24):][:8])
				v293 := v247.ExtendLo8ToUint32().AsInt32x8().ConvertToFloat32().Mul(v273)
				v294 := v247.ConcatShiftBytesRight(v247, 8).ExtendLo8ToUint32().AsInt32x8().ConvertToFloat32().Mul(v279)
				v295 := v293.Add(v294)
				v296 := v251.ExtendLo8ToUint32().AsInt32x8().ConvertToFloat32().Mul(v285)
				v297 := v251.ConcatShiftBytesRight(v251, 8).ExtendLo8ToUint32().AsInt32x8().ConvertToFloat32().Mul(v291)
				v298 := v296.Add(v297)
				v301 := v273.Add(v279)
				v302 := v285.Add(v291)
				v306 := v301.Add(v302).Mul(archsimd.BroadcastFloat32x8(v53 * float32(v67[v224])))
				v307 := v295.Add(v298).Mul(archsimd.BroadcastFloat32x8(v40 * float32(v66[v224]))).Sub(v306)
				v19 = v19.Add(v307)
				v12++
			}
		}
		var v309 [8]float32
		v19.Store(v309[0:8])
		return float32(((((((v309[0] + v309[1]) + v309[2]) + v309[3]) + v309[4]) + v309[5]) + v309[6]) + v309[7])
	} else {
		var v334 [8]float32
		for v10 = 0; v10 < v7; v10++ {
			v340 := v10 * 144
			v354 := fp16_to_fp32(uint16(v4[v340]) | uint16(uint16(v4[(v340+1)])<<8))
			v367 := fp16_to_fp32(uint16(v4[(v340+2)]) | uint16(uint16(v4[(v340+3)])<<8))
			v371 := v340 + 4
			var v380 [8]byte
			var v381 [8]byte
			v11 = 0
			for v11 < 4 {
				v386 := v4[v371+v11]
				v389 := v386 & 63
				v380[v11] = v389
				v391 := v11 + 4
				v392 := v4[v371+v391]
				v395 := v392 & 63
				v381[v11] = v395
				v398 := v4[v371+v11+8]
				v401 := v398 & 15
				v380[v391] = v401 | byte(uint32((uint32(v386)>>6)<<4))
				v381[v391] = byte((uint32(v398) >> 4) | uint32((uint32(v392)>>6)<<4))
				v11++
			}
			v12 = 0
			for v12 < 4 {
				v434 := 2 * v12
				v452 := v434 + 1
				v468 := (v10 * 0x100) + (v12 * 64)
				v472 := v468 + 32
				v477 := (v340 + 16) + (v12 * 32)
				v13 = 0
				for v13 < 8 {
					v484 := v13
					v485 := v4[v477+v484]
					v488 := v485 & 15
					v492 := v13 + 8
					v493 := v4[v477+v492]
					v496 := v493 & 15
					v500 := v13 + 16
					v501 := v4[v477+v500]
					v504 := v501 & 15
					v508 := v13 + 24
					v509 := v4[v477+v508]
					v512 := v509 & 15
					v517 := x[v468+v484]
					v522 := x[v468+v492]
					v528 := x[v468+v500]
					v533 := x[v468+v508]
					v597 := x[v472+v484]
					v602 := x[v472+v492]
					v608 := x[v472+v500]
					v613 := x[v472+v508]
					v334[v13] += (((((float32(v488) * v517) + (float32(v496) * v522)) + ((float32(v504) * v528) + (float32(v512) * v533))) * (v354 * float32(v380[v434]))) - (((v517 + v522) + (v528 + v533)) * (v367 * float32(v381[v434]))))
					v334[v13] += (((((float32(uint32(v485)>>4) * v597) + (float32(uint32(v493)>>4) * v602)) + ((float32(uint32(v501)>>4) * v608) + (float32(uint32(v509)>>4) * v613))) * (v354 * float32(v380[v452]))) - (((v597 + v602) + (v608 + v613)) * (v367 * float32(v381[v452]))))
					v13++
				}
				v12++
			}
		}
		return float32(((((((v334[0] + v334[1]) + v334[2]) + v334[3]) + v334[4]) + v334[5]) + v334[6]) + v334[7])
	}
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const C2_tensor_dot_q4_k_IRCost = uint64(694)
