//go:build !goexperiment.simd || !amd64

// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=3b1cc4d70c363ddf6b2c6723b787889a374995c6611f7701db74b3e402c951ab
package simd

func C2_tensor_gemv2_q4_k_q8_k(weight0 []byte, weight1 []byte, q8k []byte, cols int, out0 *float32, out1 *float32) {
	var v9 float32
	var v11 float32
	var v13 int
	var v14 int
	var v15 int
	var v918 int32
	var v920 int32
	var v922 int32
	var v924 int32
	var v926 int
	v9 = 0
	v11 = v9
	for v13 = 0; v13 < (cols / 0x100); v13++ {
		v613 := weight0[:]
		v615 := v13 * 144
		v618 := weight1[:]
		v623 := q8k[:]
		v625 := v13 * 0x124
		v653 := f32_from_bits(((uint32(v623[v625]) | uint32(uint32(v623[v625+1])<<8)) | uint32(uint32(v623[v625+2])<<16)) | uint32(uint32(v623[v625+3])<<24))
		v662 := v625 + 0x104
		v670 := v615 + 1
		v675 := fp16_to_fp32(uint16(v613[v615]) | uint16(uint16(v613[v670])<<8))
		v676 := v675 * v653
		v680 := v615 + 2
		v684 := v615 + 3
		v689 := fp16_to_fp32(uint16(v613[v680]) | uint16(uint16(v613[v684])<<8))
		v690 := v689 * v653
		v694 := v615 + 4
		v711 := fp16_to_fp32(uint16(v618[v615]) | uint16(uint16(v618[v670])<<8))
		v712 := v711 * v653
		v725 := fp16_to_fp32(uint16(v618[v680]) | uint16(uint16(v618[v684])<<8))
		v726 := v725 * v653
		var v735 [8]byte
		var v736 [8]byte
		var v737 [8]byte
		var v738 [8]byte
		v14 = 0
		for v14 < 4 {
			v744 := v694 + v14
			v743 := v613[v744]
			v746 := v743 & 63
			v735[v14] = v746
			v748 := v14 + 4
			v750 := v694 + v748
			v749 := v613[v750]
			v752 := v749 & 63
			v736[v14] = v752
			v756 := v694 + (v14 + 8)
			v755 := v613[v756]
			v758 := v755 & 15
			v735[v748] = v758 | byte(uint32((uint32(v743)>>6)<<4))
			v736[v748] = byte((uint32(v755) >> 4) | uint32((uint32(v749)>>6)<<4))
			v785 := v618[v744]
			v788 := v785 & 63
			v737[v14] = v788
			v791 := v618[v750]
			v794 := v791 & 63
			v738[v14] = v794
			v797 := v618[v756]
			v800 := v797 & 15
			v737[v748] = v800 | byte(uint32((uint32(v785)>>6)<<4))
			v738[v748] = byte((uint32(v797) >> 4) | uint32((uint32(v791)>>6)<<4))
			v14++
		}
		v15 = 0
		for v15 < 4 {
			v833 := 2 * v15
			v851 := v833 + 1
			v909 := (v625 + 4) + (v15 * 64)
			v918 = 0
			v920 = v918
			v922 = v920
			v924 = v922
			v926 = 0
			for v926 < 32 {
				v933 := ((v615 + 16) + (v15 * 32)) + v926
				v932 := v613[v933]
				v935 := v932 & 15
				v939 := int32(int8(v623[v909+v926]))
				v918 += (int32(v935) * v939)
				v947 := int32(int8(v623[v909+32+v926]))
				v920 += (int32(uint32(v932)>>4) * v947)
				v951 := v618[v933]
				v954 := v951 & 15
				v922 += (int32(v954) * v939)
				v924 += (int32(uint32(v951)>>4) * v947)
				v926++
			}
			v971 := 4 * v15
			v992 := int32(read_i16(v623[int(v662+(v971*2)):])) + int32(read_i16(v623[int(v662+((v971+1)*2)):]))
			v1024 := float32(int32(read_i16(v623[int(v662+((v971+2)*2)):])) + int32(read_i16(v623[int(v662+((v971+3)*2)):])))
			v9 += (((float32(v918) * (v676 * float32(v735[v833]))) - (float32(v992) * (v690 * float32(v736[v833])))) + ((float32(v920) * (v676 * float32(v735[v851]))) - (v1024 * (v690 * float32(v736[v851])))))
			v11 += (((float32(v922) * (v712 * float32(v737[v833]))) - (float32(v992) * (v726 * float32(v738[v833])))) + ((float32(v924) * (v712 * float32(v737[v851]))) - (v1024 * (v726 * float32(v738[v851])))))
			v15++
		}
	}
	*out0 = v9
	*out1 = v11
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const C2_tensor_gemv2_q4_k_q8_k_IRCost = uint64(467)
