//go:build goexperiment.simd && amd64

// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=bdd65c5e67e3d09c3438c9ef9ef9bf6e9b2a1427f5393b78d460e507de9e31fb
package simd

import "simd/archsimd"

func C2_tensor_attn_qk(q []float32, kbase []float32, pos int, stride int, scale float32, scores []float32, hd int) {
	var v7 int
	var v8 int
	var v16 archsimd.Float32x8
	var v18 archsimd.Float32x8
	var v22 int
	var v48 int
	var v63 float32
	var v101 float32
	if archsimd.X86.AVX2() {
		for v7 = 0; v7 <= pos; v7++ {
			v14 := v7 * stride
			v16 = archsimd.BroadcastFloat32x8(float32(0))
			v18 = v16
			v8 = 0
			for {
				v22 = v8 + 16
				if !(v22 <= hd) {
					break
				}
				v29 := v14 + v8
				v16 = archsimd.LoadFloat32x8(q[v8:][:8]).MulAdd(archsimd.LoadFloat32x8(kbase[v29:][:8]), v16)
				v18 = archsimd.LoadFloat32x8(q[(v8 + 8):][:8]).MulAdd(archsimd.LoadFloat32x8(kbase[int(v29+8):][:8]), v18)
				v8 = v22
			}
			for {
				v48 = v8 + 8
				if !(v48 <= hd) {
					break
				}
				v16 = archsimd.LoadFloat32x8(q[v8:][:8]).MulAdd(archsimd.LoadFloat32x8(kbase[int(v14+v8):][:8]), v16)
				v8 = v48
			}
			var v61 [8]float32
			v16.Add(v18).Store(v61[0:8])
			v63 = ((v61[0] + v61[1]) + (v61[2] + v61[3])) + ((v61[4] + v61[5]) + (v61[6] + v61[7]))
			for v8 < hd {
				v63 += (q[v8] * kbase[v14+v8])
				v8++
			}
			scores[v7] = v63 * scale
		}
	} else {
		for v7 = 0; v7 <= pos; v7++ {
			v101 = 0
			v8 = 0
			{
				_q := q[:hd]
				v8 = 0
				for v8 < hd {
					v101 += (_q[v8] * kbase[int((v7*stride)+v8)])
					v8++
				}
			}
			scores[v7] = v101 * scale
		}
	}
}

func C2_tensor_attn_av(scores []float32, vbase []float32, pos int, stride int, out []float32, hd int) {
	var v6 int
	var v7 int
	var v8 int
	var v16 archsimd.Float32x8
	var v18 archsimd.Float32x8
	var v20 archsimd.Float32x8
	var v22 archsimd.Float32x8
	var v24 archsimd.Float32x8
	var v26 archsimd.Float32x8
	var v28 archsimd.Float32x8
	var v30 archsimd.Float32x8
	var v141 int
	var v144 archsimd.Float32x8
	var v164 float32
	var v178 float32
	if archsimd.X86.AVX2() {
		if (hd % 64) == 0 {
			for v8 = 0; v8 < hd; v8 += 64 {
				v16 = archsimd.BroadcastFloat32x8(float32(0))
				v18 = v16
				v20 = v18
				v22 = v20
				v24 = v22
				v26 = v24
				v28 = v26
				v30 = v28
				v6 = 0
				for v6 <= pos {
					v37 := archsimd.BroadcastFloat32x8(scores[v6])
					v42 := (v6 * stride) + v8
					v16 = v37.MulAdd(archsimd.LoadFloat32x8(vbase[v42:][:8]), v16)
					v18 = v37.MulAdd(archsimd.LoadFloat32x8(vbase[int(v42+8):][:8]), v18)
					v20 = v37.MulAdd(archsimd.LoadFloat32x8(vbase[int(v42+16):][:8]), v20)
					v22 = v37.MulAdd(archsimd.LoadFloat32x8(vbase[int(v42+24):][:8]), v22)
					v24 = v37.MulAdd(archsimd.LoadFloat32x8(vbase[int(v42+32):][:8]), v24)
					v26 = v37.MulAdd(archsimd.LoadFloat32x8(vbase[int(v42+40):][:8]), v26)
					v28 = v37.MulAdd(archsimd.LoadFloat32x8(vbase[int(v42+48):][:8]), v28)
					v30 = v37.MulAdd(archsimd.LoadFloat32x8(vbase[int(v42+56):][:8]), v30)
					v6++
				}
				v16.Store(out[v8:][:8])
				v18.Store(out[(v8 + 8):][:8])
				v20.Store(out[(v8 + 16):][:8])
				v22.Store(out[(v8 + 24):][:8])
				v24.Store(out[(v8 + 32):][:8])
				v26.Store(out[(v8 + 40):][:8])
				v28.Store(out[(v8 + 48):][:8])
				v30.Store(out[(v8 + 56):][:8])
			}
		} else {
			v7 = 0
			for {
				v141 = v7 + 8
				if !(v141 <= hd) {
					break
				}
				v144 = archsimd.BroadcastFloat32x8(float32(0))
				for v6 = 0; v6 <= pos; v6++ {
					v144 = archsimd.BroadcastFloat32x8(scores[v6]).MulAdd(archsimd.LoadFloat32x8(vbase[int((v6*stride)+v7):][:8]), v144)
				}
				v144.Store(out[v7:][:8])
				v7 += 8
				v141++
			}
			for v7 < hd {
				v164 = 0
				for v6 = 0; v6 <= pos; v6++ {
					v164 += (scores[v6] * vbase[int((v6*stride)+v7)])
				}
				out[v7] = v164
				v7++
			}
		}
	} else {
		for v7 = 0; v7 < hd; v7++ {
			v178 = 0
			v6 = 0
			for v6 <= pos {
				v178 += (scores[v6] * vbase[int((v6*stride)+v7)])
				v6++
			}
			out[v7] = v178
		}
	}
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const (
	C2_tensor_attn_qk_IRCost = uint64(122)
	C2_tensor_attn_av_IRCost = uint64(211)
)
