//go:build !goexperiment.simd || !amd64

// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=8959a49ccf9e9cfa035c523a10eeb1f5c72e67244e83f34d35e9560085113ddd
package simd

type Block_q8_K struct {
	D  float32
	Qs [256]int8
}

func C2_tensor_gemv2_q6_k_q8_k(weight0 []byte, weight1 []byte, q8k []byte, cols int, out0 *float32, out1 *float32) {
	var v9 float32
	var v11 float32
	var v13 int
	var v14 int
	var v15 int
	var v16 int
	var v619 int32
	var v621 int32
	var v685 int32
	var v687 int32
	var v689 int32
	var v691 int32
	var v729 byte
	var v730 byte
	var v733 byte
	var v735 byte
	var v740 byte
	var v742 byte
	var v748 byte
	var v752 uint32
	var v757 byte
	var v761 uint32
	var v771 uint32
	var v780 uint32
	var v789 uint32
	var v798 uint32
	var v852 byte
	var v853 byte
	var v856 byte
	var v858 byte
	var v863 byte
	var v865 byte
	var v871 byte
	var v875 uint32
	var v880 byte
	var v884 uint32
	var v894 uint32
	var v903 uint32
	var v912 uint32
	var v921 uint32
	var v963 int32
	var v964 int32
	var v965 int32
	var v966 int32
	var v974 int
	var v987 int
	var v991 int
	var v1004 int
	var v1008 int
	var v1020 int
	var v1024 int
	v9 = 0
	v11 = v9
	for v13 = 0; v13 < (cols / 0x100); v13++ {
		v541 := weight0[:]
		v543 := v13 * 210
		v546 := weight1[:]
		v551 := q8k[:]
		v553 := v13 * 0x124
		v581 := f32_from_bits(((uint32(v551[v553]) | uint32(uint32(v551[v553+1])<<8)) | uint32(uint32(v551[v553+2])<<16)) | uint32(uint32(v551[v553+3])<<24))
		v594 := v543 + 208
		v598 := v543 + 209
		v603 := fp16_to_fp32(uint16(v541[v594]) | uint16(uint16(v541[v598])<<8))
		v617 := fp16_to_fp32(uint16(v546[v594]) | uint16(uint16(v546[v598])<<8))
		v619 = 0
		v621 = v619
		v14 = 0
		for v14 < 2 {
			v631 := v543 + (v14 * 64)
			v639 := (v543 + 128) + (v14 * 32)
			v647 := (v543 + 192) + (v14 * 8)
			v675 := (v553 + 4) + (v14 * 128)
			v680 := (v553 + 0x104) + (v14 * 16)
			v15 = 0
			for v15 < 4 {
				v685 = 0
				v687 = v685
				v689 = v687
				v691 = v689
				v16 = 0
				for v16 < 16 {
					v702 := (v15 == 0) || (v15 == 2)
					v704 := v631 + v16
					v708 := v631 + (32 + v16)
					v709 := func() byte {
						if v702 {
							return v541[v704]
						}
						return v541[v708]
					}()
					v722 := func() byte {
						if v702 {
							return v546[v704]
						}
						return v546[v708]
					}()
					v725 := v639 + v16
					v724 := v541[v725]
					v727 := v546[v725]
					if v15 == 0 {
						v733 = v709 & 15
						v735 = v724 & 3
						v729 = v733 | byte(uint32(v735)<<4)
						v740 = v722 & 15
						v742 = v727 & 3
						v730 = v740 | byte(uint32(v742)<<4)
					} else {
						if v15 == 1 {
							v748 = v709 & 15
							v752 = (uint32(v724) >> 2) & 3
							v729 = v748 | byte(v752<<4)
							v757 = v722 & 15
							v761 = (uint32(v727) >> 2) & 3
							v730 = v757 | byte(v761<<4)
						} else {
							if v15 == 2 {
								v771 = (uint32(v724) >> 4) & 3
								v729 = byte((uint32(v709) >> 4) | (v771 << 4))
								v780 = (uint32(v727) >> 4) & 3
								v730 = byte((uint32(v722) >> 4) | (v780 << 4))
							} else {
								v789 = (uint32(v724) >> 6) & 3
								v729 = byte((uint32(v709) >> 4) | (v789 << 4))
								v798 = (uint32(v727) >> 6) & 3
								v730 = byte((uint32(v722) >> 4) | (v798 << 4))
							}
						}
					}
					v809 := int32(int8(v551[int(v675+((v15*32)+v16))]))
					v685 += (int32(v729) * v809)
					v689 += (int32(v730) * v809)
					v16++
				}
				v16 = 16
				for v16 < 32 {
					v825 := (v15 == 0) || (v15 == 2)
					v827 := v631 + v16
					v831 := v631 + (32 + v16)
					v832 := func() byte {
						if v825 {
							return v541[v827]
						}
						return v541[v831]
					}()
					v845 := func() byte {
						if v825 {
							return v546[v827]
						}
						return v546[v831]
					}()
					v848 := v639 + v16
					v847 := v541[v848]
					v850 := v546[v848]
					if v15 == 0 {
						v856 = v832 & 15
						v858 = v847 & 3
						v852 = v856 | byte(uint32(v858)<<4)
						v863 = v845 & 15
						v865 = v850 & 3
						v853 = v863 | byte(uint32(v865)<<4)
					} else {
						if v15 == 1 {
							v871 = v832 & 15
							v875 = (uint32(v847) >> 2) & 3
							v852 = v871 | byte(v875<<4)
							v880 = v845 & 15
							v884 = (uint32(v850) >> 2) & 3
							v853 = v880 | byte(v884<<4)
						} else {
							if v15 == 2 {
								v894 = (uint32(v847) >> 4) & 3
								v852 = byte((uint32(v832) >> 4) | (v894 << 4))
								v903 = (uint32(v850) >> 4) & 3
								v853 = byte((uint32(v845) >> 4) | (v903 << 4))
							} else {
								v912 = (uint32(v847) >> 6) & 3
								v852 = byte((uint32(v832) >> 4) | (v912 << 4))
								v921 = (uint32(v850) >> 6) & 3
								v853 = byte((uint32(v845) >> 4) | (v921 << 4))
							}
						}
					}
					v932 := int32(int8(v551[int(v675+((v15*32)+v16))]))
					v687 += (int32(v852) * v932)
					v691 += (int32(v853) * v932)
					v16++
				}
				v941 := v15 * 2
				if v15 == 0 {
					v963 = int32(int8(v541[v647]))
					v974 = v647 + 1
					v964 = int32(int8(v541[v974]))
					v965 = int32(int8(v546[v647]))
					v966 = int32(int8(v546[v974]))
				} else {
					if v15 == 1 {
						v987 = v647 + 2
						v963 = int32(int8(v541[v987]))
						v991 = v647 + 3
						v964 = int32(int8(v541[v991]))
						v965 = int32(int8(v546[v987]))
						v966 = int32(int8(v546[v991]))
					} else {
						if v15 == 2 {
							v1004 = v647 + 4
							v963 = int32(int8(v541[v1004]))
							v1008 = v647 + 5
							v964 = int32(int8(v541[v1008]))
							v965 = int32(int8(v546[v1004]))
							v966 = int32(int8(v546[v1008]))
						} else {
							v1020 = v647 + 6
							v963 = int32(int8(v541[v1020]))
							v1024 = v647 + 7
							v964 = int32(int8(v541[v1024]))
							v965 = int32(int8(v546[v1020]))
							v966 = int32(int8(v546[v1024]))
						}
					}
				}
				v1035 := int32(32) * int32(read_i16(v551[int(v680+(v941*2)):]))
				v1039 := int32(32) * int32(read_i16(v551[int(v680+((v941+1)*2)):]))
				v619 += (((v685 - v1035) * v963) + ((v687 - v1039) * v964))
				v621 += (((v689 - v1035) * v965) + ((v691 - v1039) * v966))
				v15++
			}
			v14++
		}
		v9 += (float32(v619) * (v603 * v581))
		v11 += (float32(v621) * (v617 * v581))
	}
	*out0 = v9
	*out1 = v11
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const C2_tensor_gemv2_q6_k_q8_k_IRCost = uint64(586)
