//go:build !goexperiment.simd || !amd64

// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=8021bee6f4ba9a3d237cb40ac9a3cdf2cab17a061dcf1a35015a9f991f591106
package simd

func C2_tensor_dot_q6_k(weight []byte, x []float32, cols int) float32 {
	var v10 int
	var v11 int
	var v12 int
	var v14 int
	v4 := weight[:]
	_ = float32(0)
	var v358 [8]float32
	for v10 = 0; v10 < (cols / 0x100); v10++ {
		v364 := v10 * 210
		v389 := fp16_to_fp32(uint16(v4[(v364+208)]) | uint16(uint16(v4[(v364+209)])<<8))
		v11 = 0
		for v11 < 2 {
			v402 := v364 + (v11 * 64)
			v407 := (v364 + 128) + (v11 * 32)
			v412 := (v364 + 192) + (v11 * 8)
			v417 := (v10 * 0x100) + (v11 * 128)
			var v418 [8]float32
			var v419 [8]float32
			var v420 [8]float32
			var v421 [8]float32
			v14 = 0
			for v14 < 2 {
				v426 := v14
				v433 := v389 * float32(int8(v4[v412+v426]))
				v440 := v389 * float32(int8(v4[v412+v426+2]))
				v447 := v389 * float32(int8(v4[v412+v426+4]))
				v454 := v389 * float32(int8(v4[v412+v426+6]))
				v12 = 0
				for v12 < 8 {
					v461 := v14 * 16
					v462 := v461 + v12
					v468 := (v461 + 8) + v12
					v470 := v4[v407+v462]
					v473 := v4[v407+v468]
					v476 := v4[v402+v462]
					v479 := v476 & 15
					v483 := v470 & 3
					v491 := v4[v402+v468]
					v494 := v491 & 15
					v498 := v473 & 3
					v418[v12] += (((float32(int(v479|byte(uint32(v483)<<4))-32) * v433) * x[v417+v462]) + ((float32(int(v494|byte(uint32(v498)<<4))-32) * v433) * x[v417+v468]))
					v520 := v462 + 32
					v521 := v4[v402+v520]
					v524 := v521 & 15
					v528 := (uint32(v470) >> 2) & 3
					v537 := v468 + 32
					v538 := v4[v402+v537]
					v541 := v538 & 15
					v545 := (uint32(v473) >> 2) & 3
					v419[v12] += (((float32(int(v524|byte(uint32(v528<<4)))-32) * v440) * x[v417+v520]) + ((float32(int(v541|byte(uint32(v545<<4)))-32) * v440) * x[v417+v537]))
					v577 := (uint32(v470) >> 4) & 3
					v592 := (uint32(v473) >> 4) & 3
					v420[v12] += (((float32(int((uint32(v476)>>4)|uint32(v577<<4))-32) * v447) * x[v417+v462+64]) + ((float32(int((uint32(v491)>>4)|uint32(v592<<4))-32) * v447) * x[v417+v468+64]))
					v626 := (uint32(v470) >> 6) & 3
					v643 := (uint32(v473) >> 6) & 3
					v421[v12] += (((float32(int((uint32(v521)>>4)|uint32(v626<<4))-32) * v454) * x[v417+v462+96]) + ((float32(int((uint32(v538)>>4)|uint32(v643<<4))-32) * v454) * x[v417+v468+96]))
					v12++
				}
				v14++
			}
			v12 = 0
			v358[0] += ((v418[0] + v419[0]) + (v420[0] + v421[0]))
			v358[1] += ((v418[1] + v419[1]) + (v420[1] + v421[1]))
			v358[2] += ((v418[2] + v419[2]) + (v420[2] + v421[2]))
			v358[3] += ((v418[3] + v419[3]) + (v420[3] + v421[3]))
			v358[4] += ((v418[4] + v419[4]) + (v420[4] + v421[4]))
			v358[5] += ((v418[5] + v419[5]) + (v420[5] + v421[5]))
			v358[6] += ((v418[6] + v419[6]) + (v420[6] + v421[6]))
			v358[7] += ((v418[7] + v419[7]) + (v420[7] + v421[7]))
			v11++
		}
	}
	return float32(((((((v358[0] + v358[1]) + v358[2]) + v358[3]) + v358[4]) + v358[5]) + v358[6]) + v358[7])
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const C2_tensor_dot_q6_k_IRCost = uint64(373)
