//go:build goexperiment.simd && amd64

// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=545d530957861b5d7da5285dbfa00a37b39d6ce877f71edf49572b0b7c65fa0f
package simd

import "simd/archsimd"

func C2_tensor_gemv2_q4_k_q8_k(weight0 []byte, weight1 []byte, q8k []byte, cols int, out0 *float32, out1 *float32) {
	var v9 float32
	var v11 float32
	var v13 int
	var v14 int
	var v15 int
	var v16 int
	var v389 int32
	var v391 int32
	var v393 int32
	var v395 int32
	var v918 int32
	var v920 int32
	var v922 int32
	var v924 int32
	var v926 int
	v8 := cols / 0x100
	v9 = 0
	v11 = v9
	if archsimd.X86.AVX2() {
		v20 := archsimd.BroadcastUint8x32(byte(15))
		v23 := archsimd.BroadcastInt16x16(int16(1))
		for v13 = 0; v13 < v8; v13++ {
			v28 := weight0[:]
			v30 := v13 * 144
			v33 := weight1[:]
			v38 := q8k[:]
			v40 := v13 * 0x124
			v68 := f32_from_bits(((uint32(v38[v40]) | uint32(uint32(v38[v40+1])<<8)) | uint32(uint32(v38[v40+2])<<16)) | uint32(uint32(v38[v40+3])<<24))
			v77 := v40 + 0x104
			v85 := v30 + 1
			v90 := fp16_to_fp32(uint16(v28[v30]) | uint16(uint16(v28[v85])<<8))
			v91 := v90 * v68
			v95 := v30 + 2
			v99 := v30 + 3
			v104 := fp16_to_fp32(uint16(v28[v95]) | uint16(uint16(v28[v99])<<8))
			v105 := v104 * v68
			v109 := v30 + 4
			v126 := fp16_to_fp32(uint16(v33[v30]) | uint16(uint16(v33[v85])<<8))
			v127 := v126 * v68
			v140 := fp16_to_fp32(uint16(v33[v95]) | uint16(uint16(v33[v99])<<8))
			v141 := v140 * v68
			var v150 [8]byte
			var v151 [8]byte
			var v152 [8]byte
			var v153 [8]byte
			v14 = 0
			for v14 < 4 {
				v159 := v109 + v14
				v158 := v28[v159]
				v161 := v158 & 63
				v150[v14] = v161
				v163 := v14 + 4
				v165 := v109 + v163
				v164 := v28[v165]
				v167 := v164 & 63
				v151[v14] = v167
				v171 := v109 + (v14 + 8)
				v170 := v28[v171]
				v173 := v170 & 15
				v150[v163] = v173 | byte(uint32((uint32(v158)>>6)<<4))
				v151[v163] = byte((uint32(v170) >> 4) | uint32((uint32(v164)>>6)<<4))
				v200 := v33[v159]
				v203 := v200 & 63
				v152[v14] = v203
				v206 := v33[v165]
				v209 := v206 & 63
				v153[v14] = v209
				v212 := v33[v171]
				v215 := v212 & 15
				v152[v163] = v215 | byte(uint32((uint32(v200)>>6)<<4))
				v153[v163] = byte((uint32(v212) >> 4) | uint32((uint32(v206)>>6)<<4))
				v14++
			}
			v15 = 0
			for v15 < 4 {
				v248 := 2 * v15
				v266 := v248 + 1
				v314 := (v40 + 4) + (v15 * 64)
				v326 := archsimd.LoadUint8x32(v38[v314:][:32])
				v330 := archsimd.LoadUint8x32(v38[int(v314+32):][:32])
				v335 := (v30 + 16) + (v15 * 32)
				v339 := archsimd.LoadUint8x32(v28[v335:][:32])
				v362 := archsimd.LoadUint8x32(v33[v335:][:32])
				var v377 [32]byte
				var v378 [32]byte
				var v379 [32]byte
				var v380 [32]byte
				v339.And(v20).DotProductPairsSaturated(v326.AsInt8x32()).DotProductPairs(v23).AsUint8x32().Store(v377[0:32])
				v339.AsUint16x16().ShiftAllRight(4).AsUint8x32().And(v20).DotProductPairsSaturated(v330.AsInt8x32()).DotProductPairs(v23).AsUint8x32().Store(v378[0:32])
				v362.And(v20).DotProductPairsSaturated(v326.AsInt8x32()).DotProductPairs(v23).AsUint8x32().Store(v379[0:32])
				v362.AsUint16x16().ShiftAllRight(4).AsUint8x32().And(v20).DotProductPairsSaturated(v330.AsInt8x32()).DotProductPairs(v23).AsUint8x32().Store(v380[0:32])
				v389 = 0
				v391 = v389
				v393 = v391
				v395 = v393
				v16 = 0
				for v16 < 8 {
					v402 := v16 * 4
					v408 := v402 + 1
					v417 := v402 + 2
					v426 := v402 + 3
					v389 += int32(((uint32(v377[v402]) | uint32(uint32(v377[v408])<<8)) | uint32(uint32(v377[v417])<<16)) | uint32(uint32(v377[v426])<<24))
					v391 += int32(((uint32(v378[v402]) | uint32(uint32(v378[v408])<<8)) | uint32(uint32(v378[v417])<<16)) | uint32(uint32(v378[v426])<<24))
					v393 += int32(((uint32(v379[v402]) | uint32(uint32(v379[v408])<<8)) | uint32(uint32(v379[v417])<<16)) | uint32(uint32(v379[v426])<<24))
					v395 += int32(((uint32(v380[v402]) | uint32(uint32(v380[v408])<<8)) | uint32(uint32(v380[v417])<<16)) | uint32(uint32(v380[v426])<<24))
					v16++
				}
				v535 := 4 * v15
				v584 := float32(int32(read_i16(v38[int(v77+(v535*2)):])) + int32(read_i16(v38[int(v77+((v535+1)*2)):])))
				v590 := float32(int32(read_i16(v38[int(v77+((v535+2)*2)):])) + int32(read_i16(v38[int(v77+((v535+3)*2)):])))
				v9 += (((float32(v389) * (v91 * float32(v150[v248]))) - (v584 * (v105 * float32(v151[v248])))) + ((float32(v391) * (v91 * float32(v150[v266]))) - (v590 * (v105 * float32(v151[v266])))))
				v11 += (((float32(v393) * (v127 * float32(v152[v248]))) - (v584 * (v141 * float32(v153[v248])))) + ((float32(v395) * (v127 * float32(v152[v266]))) - (v590 * (v141 * float32(v153[v266])))))
				v15++
			}
		}
		*out0 = v9
		*out1 = v11
		return
	} else {
		for v13 = 0; v13 < v8; v13++ {
			v613 := weight0[:]
			v615 := v13 * 144
			v618 := weight1[:]
			v623 := q8k[:]
			v625 := v13 * 0x124
			v653 := f32_from_bits(((uint32(v623[v625]) | uint32(uint32(v623[v625+1])<<8)) | uint32(uint32(v623[v625+2])<<16)) | uint32(uint32(v623[v625+3])<<24))
			v662 := v625 + 0x104
			v670 := v615 + 1
			v675 := fp16_to_fp32(uint16(v613[v615]) | uint16(uint16(v613[v670])<<8))
			v676 := v675 * v653
			v680 := v615 + 2
			v684 := v615 + 3
			v689 := fp16_to_fp32(uint16(v613[v680]) | uint16(uint16(v613[v684])<<8))
			v690 := v689 * v653
			v694 := v615 + 4
			v711 := fp16_to_fp32(uint16(v618[v615]) | uint16(uint16(v618[v670])<<8))
			v712 := v711 * v653
			v725 := fp16_to_fp32(uint16(v618[v680]) | uint16(uint16(v618[v684])<<8))
			v726 := v725 * v653
			var v735 [8]byte
			var v736 [8]byte
			var v737 [8]byte
			var v738 [8]byte
			v14 = 0
			for v14 < 4 {
				v744 := v694 + v14
				v743 := v613[v744]
				v746 := v743 & 63
				v735[v14] = v746
				v748 := v14 + 4
				v750 := v694 + v748
				v749 := v613[v750]
				v752 := v749 & 63
				v736[v14] = v752
				v756 := v694 + (v14 + 8)
				v755 := v613[v756]
				v758 := v755 & 15
				v735[v748] = v758 | byte(uint32((uint32(v743)>>6)<<4))
				v736[v748] = byte((uint32(v755) >> 4) | uint32((uint32(v749)>>6)<<4))
				v785 := v618[v744]
				v788 := v785 & 63
				v737[v14] = v788
				v791 := v618[v750]
				v794 := v791 & 63
				v738[v14] = v794
				v797 := v618[v756]
				v800 := v797 & 15
				v737[v748] = v800 | byte(uint32((uint32(v785)>>6)<<4))
				v738[v748] = byte((uint32(v797) >> 4) | uint32((uint32(v791)>>6)<<4))
				v14++
			}
			v15 = 0
			for v15 < 4 {
				v833 := 2 * v15
				v851 := v833 + 1
				v909 := (v625 + 4) + (v15 * 64)
				v918 = 0
				v920 = v918
				v922 = v920
				v924 = v922
				v926 = 0
				for v926 < 32 {
					v933 := ((v615 + 16) + (v15 * 32)) + v926
					v932 := v613[v933]
					v935 := v932 & 15
					v939 := int32(int8(v623[v909+v926]))
					v918 += (int32(v935) * v939)
					v947 := int32(int8(v623[v909+32+v926]))
					v920 += (int32(uint32(v932)>>4) * v947)
					v951 := v618[v933]
					v954 := v951 & 15
					v922 += (int32(v954) * v939)
					v924 += (int32(uint32(v951)>>4) * v947)
					v926++
				}
				v971 := 4 * v15
				v992 := int32(read_i16(v623[int(v662+(v971*2)):])) + int32(read_i16(v623[int(v662+((v971+1)*2)):]))
				v1024 := float32(int32(read_i16(v623[int(v662+((v971+2)*2)):])) + int32(read_i16(v623[int(v662+((v971+3)*2)):])))
				v9 += (((float32(v918) * (v676 * float32(v735[v833]))) - (float32(v992) * (v690 * float32(v736[v833])))) + ((float32(v920) * (v676 * float32(v735[v851]))) - (v1024 * (v690 * float32(v736[v851])))))
				v11 += (((float32(v922) * (v712 * float32(v737[v833]))) - (float32(v992) * (v726 * float32(v738[v833])))) + ((float32(v924) * (v712 * float32(v737[v851]))) - (v1024 * (v726 * float32(v738[v851])))))
				v15++
			}
		}
		*out0 = v9
		*out1 = v11
	}
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const C2_tensor_gemv2_q4_k_q8_k_IRCost = uint64(1084)
