//go:build !goexperiment.simd || !amd64

// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=ee7e1a458e8e56da62ad06440ddf6dee0833a924da68055cdafe722633c375ed
package simd

import "math"

func f32_from_bits(u uint32) float32 {
	return math.Float32frombits(u)
}

var fp16LUT [65536]float32

func init() {
	for i := 0; i < 65536; i++ {
		fp16LUT[i] = computeFP16ToF32(uint16(i))
	}
}

func computeFP16ToF32(h uint16) float32 {
	var v7 uint32
	var v12 uint32
	var v15 uint32
	var v20 uint32
	var v38 float32
	var v45 float32
	v6 := uint32(uint32(uint16(h>>15)) << 31)
	v11 := uint16(h>>10) & 31
	v7 = uint32(v11)
	v14 := h & 0x3ff
	v12 = uint32(v14)
	if v7 == 0 {
		if v12 == 0 {
			return float32(0)
		}
		for {
			v20 = v12 & 0x400
			if v20 != 0 {
				break
			}
			v12 = uint32(v12 << 1)
			v7--
		}
		v7++
		v12 &= 0x3ff
		v7 = (v7 + 0x70) << 23
		v12 <<= 13
		v15 = (v6 | v7) | v12
		v38 = f32_from_bits(v15)
		return v38
	}
	if v7 == 31 {
		v15 = (v6 | 0x7f800000) | (v12 << 13)
		v45 = f32_from_bits(v15)
		return v45
	}
	v7 = uint32((v7 + 0x70) << 23)
	v12 = uint32(v12 << 13)
	v15 = (v6 | v7) | v12
	v54 := f32_from_bits(v15)
	return float32(v54)
}

func fp16_to_fp32(h uint16) float32 {
	return fp16LUT[h]
}

func C2_tensor_dot_q8_0(weight []byte, x []float32, cols int) float32 {
	var v10 int
	var v11 int
	v4 := weight[:]
	_ = float32(0)
	var v131 [8]float32
	for v10 = 0; v10 < (cols / 32); v10++ {
		v137 := v10 * 34
		v152 := fp16_to_fp32(uint16(v4[v137]) | uint16(uint16(v4[(v137+1)])<<8))
		v156 := v137 + 2
		v160 := v10 * 32
		v11 = 0
		for v11 < 8 {
			v168 := v11
			v179 := v11 + 8
			v190 := v11 + 16
			v201 := v11 + 24
			v131[v11] += ((((float32(int8(v4[v156+v168])) * x[v160+v168]) + (float32(int8(v4[v156+v179])) * x[v160+v179])) + ((float32(int8(v4[v156+v190])) * x[v160+v190]) + (float32(int8(v4[v156+v201])) * x[v160+v201]))) * v152)
			v11++
		}
	}
	return float32(((((((v131[0] + v131[1]) + v131[2]) + v131[3]) + v131[4]) + v131[5]) + v131[6]) + v131[7])
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const (
	F32_from_bits_IRCost      = uint64(6)
	Fp16_to_fp32_IRCost       = uint64(69)
	C2_tensor_dot_q8_0_IRCost = uint64(123)
)
