//go:build goexperiment.simd && amd64

// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=adef6547cfdd058782e61ec989cc165051bcc2525c5ced9e3d30375cbe32aff0
package simd

import "simd/archsimd"

func __avx2() int {
	return 0
}

func read_i16(p []byte) int16 {
	return int16(uint16(p[0]) | uint16(uint16(p[1])<<8))
}

func C2_tensor_dot_q4_k_q8_k(weight []byte, q8k []byte, cols int) float32 {
	var v6 float32
	var v8 int
	var v9 int
	var v10 int
	var v11 int
	var v238 int32
	var v240 int32
	var v242 int
	var v562 int32
	var v564 int32
	v5 := cols / 0x100
	v6 = 0
	if archsimd.X86.AVX2() {
		v15 := archsimd.BroadcastUint8x32(byte(15))
		v18 := archsimd.BroadcastInt16x16(int16(1))
		for v8 = 0; v8 < v5; v8++ {
			v23 := weight[:]
			v25 := v8 * 144
			v28 := q8k[:]
			v30 := v8 * 0x124
			v58 := f32_from_bits(((uint32(v28[v30]) | uint32(uint32(v28[v30+1])<<8)) | uint32(uint32(v28[v30+2])<<16)) | uint32(uint32(v28[v30+3])<<24))
			v71 := fp16_to_fp32(uint16(v23[v25]) | uint16(uint16(v23[(v25+1)])<<8))
			v72 := v71 * v58
			v85 := fp16_to_fp32(uint16(v23[(v25+2)]) | uint16(uint16(v23[(v25+3)])<<8))
			v86 := v85 * v58
			v90 := v25 + 4
			v103 := v30 + 0x104
			var v104 [8]byte
			var v105 [8]byte
			v9 = 0
			for v9 < 4 {
				v110 := v23[v90+v9]
				v113 := v110 & 63
				v104[v9] = v113
				v115 := v9 + 4
				v116 := v23[v90+v115]
				v119 := v116 & 63
				v105[v9] = v119
				v122 := v23[v90+v9+8]
				v125 := v122 & 15
				v104[v115] = v125 | byte(uint32((uint32(v110)>>6)<<4))
				v105[v115] = byte((uint32(v122) >> 4) | uint32((uint32(v116)>>6)<<4))
				v9++
			}
			v10 = 0
			for v10 < 4 {
				v158 := 2 * v10
				v176 := v158 + 1
				v196 := archsimd.LoadUint8x32(v23[int((v25+16)+(v10*32)):][:32])
				v207 := (v30 + 4) + (v10 * 64)
				var v232 [32]byte
				var v233 [32]byte
				v196.And(v15).DotProductPairsSaturated(archsimd.LoadUint8x32(v28[v207:][:32]).AsInt8x32()).DotProductPairs(v18).AsUint8x32().Store(v232[0:32])
				v196.AsUint16x16().ShiftAllRight(4).AsUint8x32().And(v15).DotProductPairsSaturated(archsimd.LoadUint8x32(v28[int(v207+32):][:32]).AsInt8x32()).DotProductPairs(v18).AsUint8x32().Store(v233[0:32])
				v238 = 0
				v240 = v238
				v242 = 0
				for v242 < 8 {
					v248 := v242 * 4
					v254 := v248 + 1
					v263 := v248 + 2
					v272 := v248 + 3
					v238 += int32(((uint32(v232[v248]) | uint32(uint32(v232[v254])<<8)) | uint32(uint32(v232[v263])<<16)) | uint32(uint32(v232[v272])<<24))
					v240 += int32(((uint32(v233[v248]) | uint32(uint32(v233[v254])<<8)) | uint32(uint32(v233[v263])<<16)) | uint32(uint32(v233[v272])<<24))
					v242++
				}
				v315 := 4 * v10
				v6 += (((float32(v238) * (v72 * float32(v104[v158]))) - (float32(int32(read_i16(v28[int(v103+(v315*2)):]))+int32(read_i16(v28[int(v103+((v315+1)*2)):]))) * (v86 * float32(v105[v158])))) + ((float32(v240) * (v72 * float32(v104[v176]))) - (float32(int32(read_i16(v28[int(v103+((v315+2)*2)):]))+int32(read_i16(v28[int(v103+((v315+3)*2)):]))) * (v86 * float32(v105[v176])))))
				v10++
			}
		}
		return v6
	} else {
		for v8 = 0; v8 < v5; v8++ {
			v379 := weight[:]
			v381 := v8 * 144
			v384 := q8k[:]
			v386 := v8 * 0x124
			v414 := f32_from_bits(((uint32(v384[v386]) | uint32(uint32(v384[v386+1])<<8)) | uint32(uint32(v384[v386+2])<<16)) | uint32(uint32(v384[v386+3])<<24))
			v427 := fp16_to_fp32(uint16(v379[v381]) | uint16(uint16(v379[(v381+1)])<<8))
			v428 := v427 * v414
			v441 := fp16_to_fp32(uint16(v379[(v381+2)]) | uint16(uint16(v379[(v381+3)])<<8))
			v442 := v441 * v414
			v446 := v381 + 4
			v459 := v386 + 0x104
			var v460 [8]byte
			var v461 [8]byte
			v9 = 0
			for v9 < 4 {
				v466 := v379[v446+v9]
				v469 := v466 & 63
				v460[v9] = v469
				v471 := v9 + 4
				v472 := v379[v446+v471]
				v475 := v472 & 63
				v461[v9] = v475
				v478 := v379[v446+v9+8]
				v481 := v478 & 15
				v460[v471] = v481 | byte(uint32((uint32(v466)>>6)<<4))
				v461[v471] = byte((uint32(v478) >> 4) | uint32((uint32(v472)>>6)<<4))
				v9++
			}
			v10 = 0
			for v10 < 4 {
				v514 := 2 * v10
				v532 := v514 + 1
				v553 := (v386 + 4) + (v10 * 64)
				v562 = 0
				v564 = v562
				v11 = 0
				for v11 < 32 {
					v570 := v379[int(((v381+16)+(v10*32))+v11)]
					v573 := v570 & 15
					v562 += (int32(v573) * int32(int8(v384[v553+v11])))
					v564 += (int32(uint32(v570)>>4) * int32(int8(v384[v553+32+v11])))
					v11++
				}
				v592 := 4 * v10
				v6 += (((float32(v562) * (v428 * float32(v460[v514]))) - (float32(int32(read_i16(v384[int(v459+(v592*2)):]))+int32(read_i16(v384[int(v459+((v592+1)*2)):]))) * (v442 * float32(v461[v514])))) + ((float32(v564) * (v428 * float32(v460[v532]))) - (float32(int32(read_i16(v384[int(v459+((v592+2)*2)):]))+int32(read_i16(v384[int(v459+((v592+3)*2)):]))) * (v442 * float32(v461[v532])))))
				v10++
			}
		}
		return v6
	}
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const (
	__avx2_IRCost                  = uint64(2)
	Read_i16_IRCost                = uint64(11)
	C2_tensor_dot_q4_k_q8_k_IRCost = uint64(681)
)
