//go:build !goexperiment.simd || !amd64

// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=54246a289fd6b91e5b6abc3655bfa103d4257207e347d5dab3603e374e35931d
package simd

func C2_tensor_dot_q4_k(weight []byte, x []float32, cols int) float32 {
	var v10 int
	var v11 int
	var v12 int
	var v13 int
	v4 := weight[:]
	_ = float32(0)
	var v334 [8]float32
	for v10 = 0; v10 < (cols / 0x100); v10++ {
		v340 := v10 * 144
		v354 := fp16_to_fp32(uint16(v4[v340]) | uint16(uint16(v4[(v340+1)])<<8))
		v367 := fp16_to_fp32(uint16(v4[(v340+2)]) | uint16(uint16(v4[(v340+3)])<<8))
		v371 := v340 + 4
		var v380 [8]byte
		var v381 [8]byte
		v11 = 0
		for v11 < 4 {
			v386 := v4[v371+v11]
			v389 := v386 & 63
			v380[v11] = v389
			v391 := v11 + 4
			v392 := v4[v371+v391]
			v395 := v392 & 63
			v381[v11] = v395
			v398 := v4[v371+v11+8]
			v401 := v398 & 15
			v380[v391] = v401 | byte(uint32((uint32(v386)>>6)<<4))
			v381[v391] = byte((uint32(v398) >> 4) | uint32((uint32(v392)>>6)<<4))
			v11++
		}
		v12 = 0
		for v12 < 4 {
			v434 := 2 * v12
			v452 := v434 + 1
			v468 := (v10 * 0x100) + (v12 * 64)
			v472 := v468 + 32
			v477 := (v340 + 16) + (v12 * 32)
			v13 = 0
			for v13 < 8 {
				v484 := v13
				v485 := v4[v477+v484]
				v488 := v485 & 15
				v492 := v13 + 8
				v493 := v4[v477+v492]
				v496 := v493 & 15
				v500 := v13 + 16
				v501 := v4[v477+v500]
				v504 := v501 & 15
				v508 := v13 + 24
				v509 := v4[v477+v508]
				v512 := v509 & 15
				v517 := x[v468+v484]
				v522 := x[v468+v492]
				v528 := x[v468+v500]
				v533 := x[v468+v508]
				v597 := x[v472+v484]
				v602 := x[v472+v492]
				v608 := x[v472+v500]
				v613 := x[v472+v508]
				v334[v13] += (((((float32(v488) * v517) + (float32(v496) * v522)) + ((float32(v504) * v528) + (float32(v512) * v533))) * (v354 * float32(v380[v434]))) - (((v517 + v522) + (v528 + v533)) * (v367 * float32(v381[v434]))))
				v334[v13] += (((((float32(uint32(v485)>>4) * v597) + (float32(uint32(v493)>>4) * v602)) + ((float32(uint32(v501)>>4) * v608) + (float32(uint32(v509)>>4) * v613))) * (v354 * float32(v380[v452]))) - (((v597 + v602) + (v608 + v613)) * (v367 * float32(v381[v452]))))
				v13++
			}
			v12++
		}
	}
	return float32(((((((v334[0] + v334[1]) + v334[2]) + v334[3]) + v334[4]) + v334[5]) + v334[6]) + v334[7])
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const C2_tensor_dot_q4_k_IRCost = uint64(362)
