//go:build goexperiment.simd && amd64

// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=2a1639381c3164d3feb50b7ef385a071a26bad7f352488eb5efad22e2f62ed36
package simd

import (
	"math"
	"simd/archsimd"
)

func f32_from_bits(u uint32) float32 {
	return math.Float32frombits(u)
}

var fp16LUT [65536]float32

func init() {
	for i := 0; i < 65536; i++ {
		fp16LUT[i] = computeFP16ToF32(uint16(i))
	}
}

func computeFP16ToF32(h uint16) float32 {
	var v7 uint32
	var v12 uint32
	var v15 uint32
	var v20 uint32
	var v38 float32
	var v45 float32
	v6 := uint32(uint32(uint16(h>>15)) << 31)
	v11 := uint16(h>>10) & 31
	v7 = uint32(v11)
	v14 := h & 0x3ff
	v12 = uint32(v14)
	if v7 == 0 {
		if v12 == 0 {
			return float32(0)
		}
		for {
			v20 = v12 & 0x400
			if v20 != 0 {
				break
			}
			v12 = uint32(v12 << 1)
			v7--
		}
		v7++
		v12 &= 0x3ff
		v7 = (v7 + 0x70) << 23
		v12 <<= 13
		v15 = (v6 | v7) | v12
		v38 = f32_from_bits(v15)
		return v38
	}
	if v7 == 31 {
		v15 = (v6 | 0x7f800000) | (v12 << 13)
		v45 = f32_from_bits(v15)
		return v45
	}
	v7 = uint32((v7 + 0x70) << 23)
	v12 = uint32(v12 << 13)
	v15 = (v6 | v7) | v12
	v54 := f32_from_bits(v15)
	return float32(v54)
}

func fp16_to_fp32(h uint16) float32 {
	return fp16LUT[h]
}

func C2_tensor_dot_q8_0(weight []byte, x []float32, cols int) float32 {
	var v10 int
	var v11 int
	var v13 archsimd.Float32x8
	v4 := weight[:]
	v7 := cols / 32
	_ = float32(0)
	if archsimd.X86.AVX2() {
		v13 = archsimd.BroadcastFloat32x8(float32(0))
		for v10 = 0; v10 < v7; v10++ {
			v20 := v10 * 34
			_blk_v20 := v4[v20 : v20+34]
			_ = _blk_v20[33]
			v35 := fp16_to_fp32(uint16(_blk_v20[0]) | uint16(uint16(_blk_v20[1])<<8))
			v45 := v10 * 32
			_blk_v45 := x[v45 : v45+32]
			_ = _blk_v45[31]
			v50 := archsimd.LoadUint8x16(_blk_v20[2:18])
			v57 := archsimd.LoadUint8x16(_blk_v20[18:34])
			v64 := v50.AsInt8x16().ExtendLo8ToInt32().ConvertToFloat32().Mul(archsimd.LoadFloat32x8(_blk_v45[0:8]))
			v76 := v50.ConcatShiftBytesRight(v50, 8).AsInt8x16().ExtendLo8ToInt32().ConvertToFloat32().Mul(archsimd.LoadFloat32x8(_blk_v45[8:16]))
			v86 := v57.AsInt8x16().ExtendLo8ToInt32().ConvertToFloat32().Mul(archsimd.LoadFloat32x8(_blk_v45[16:24]))
			v98 := v57.ConcatShiftBytesRight(v57, 8).AsInt8x16().ExtendLo8ToInt32().ConvertToFloat32().Mul(archsimd.LoadFloat32x8(_blk_v45[24:32]))
			v100 := v64.Add(v76)
			v101 := v86.Add(v98)
			v104 := v100.Add(v101).Mul(archsimd.BroadcastFloat32x8(v35))
			v13 = v13.Add(v104)
		}
		var v106 [8]float32
		v13.Store(v106[0:8])
		return float32(((((((v106[0] + v106[1]) + v106[2]) + v106[3]) + v106[4]) + v106[5]) + v106[6]) + v106[7])
	} else {
		var v131 [8]float32
		for v10 = 0; v10 < v7; v10++ {
			v137 := v10 * 34
			v152 := fp16_to_fp32(uint16(v4[v137]) | uint16(uint16(v4[(v137+1)])<<8))
			v156 := v137 + 2
			v160 := v10 * 32
			v11 = 0
			for v11 < 8 {
				v168 := v11
				v179 := v11 + 8
				v190 := v11 + 16
				v201 := v11 + 24
				v131[v11] += ((((float32(int8(v4[v156+v168])) * x[v160+v168]) + (float32(int8(v4[v156+v179])) * x[v160+v179])) + ((float32(int8(v4[v156+v190])) * x[v160+v190]) + (float32(int8(v4[v156+v201])) * x[v160+v201]))) * v152)
				v11++
			}
		}
		return float32(((((((v131[0] + v131[1]) + v131[2]) + v131[3]) + v131[4]) + v131[5]) + v131[6]) + v131[7])
	}
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const (
	F32_from_bits_IRCost      = uint64(6)
	Fp16_to_fp32_IRCost       = uint64(69)
	C2_tensor_dot_q8_0_IRCost = uint64(246)
)
