//go:build goexperiment.simd && amd64

// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=c24000ee479f4f750a1010578e1fa1a3f7035209f1ee087e82d417a1d66675a4
package simd

import "simd/archsimd"

func C2_tensor_dot_q6_k(weight []byte, x []float32, cols int) float32 {
	var v10 int
	var v11 int
	var v12 int
	var v14 int
	var v25 archsimd.Float32x8
	var v86 archsimd.Float32x8
	var v88 archsimd.Float32x8
	var v90 archsimd.Float32x8
	var v92 archsimd.Float32x8
	v4 := weight[:]
	v7 := cols / 0x100
	_ = float32(0)
	if archsimd.X86.AVX2() {
		v18 := archsimd.BroadcastUint8x16(byte(15))
		v21 := archsimd.BroadcastUint8x16(byte(3))
		v24 := archsimd.BroadcastUint8x16(byte(32))
		v25 = archsimd.BroadcastFloat32x8(float32(0))
		for v10 = 0; v10 < v7; v10++ {
			v32 := v10 * 210
			v57 := fp16_to_fp32(uint16(v4[(v32+208)]) | uint16(uint16(v4[(v32+209)])<<8))
			v11 = 0
			for v11 < 2 {
				v70 := v32 + (v11 * 64)
				v80 := (v32 + 192) + (v11 * 8)
				v85 := (v10 * 0x100) + (v11 * 128)
				v86 = archsimd.BroadcastFloat32x8(float32(0))
				v88 = v86
				v90 = v88
				v92 = v90
				v14 = 0
				for v14 < 2 {
					v98 := v14
					v106 := archsimd.BroadcastFloat32x8(v57 * float32(int8(v4[v80+v98])))
					v114 := archsimd.BroadcastFloat32x8(v57 * float32(int8(v4[v80+v98+2])))
					v122 := archsimd.BroadcastFloat32x8(v57 * float32(int8(v4[v80+v98+4])))
					v130 := archsimd.BroadcastFloat32x8(v57 * float32(int8(v4[v80+v98+6])))
					v133 := v14 * 16
					v138 := archsimd.LoadUint8x16(v4[int(v70+v133):][:16])
					v149 := archsimd.LoadUint8x16(v4[int((v70+32)+v133):][:16])
					v157 := archsimd.LoadUint8x16(v4[int(((v32+128)+(v11*32))+v133):][:16])
					v164 := v138.And(v18).Or(v157.And(v21).AsUint16x8().ShiftAllLeft(4).AsUint8x16()).Sub(v24)
					v173 := v149.And(v18).Or(v157.AsUint16x8().ShiftAllRight(2).AsUint8x16().And(v21).AsUint16x8().ShiftAllLeft(4).AsUint8x16()).Sub(v24)
					v184 := v138.AsUint16x8().ShiftAllRight(4).AsUint8x16().And(v18).Or(v157.AsUint16x8().ShiftAllRight(4).AsUint8x16().And(v21).AsUint16x8().ShiftAllLeft(4).AsUint8x16()).Sub(v24)
					v195 := v149.AsUint16x8().ShiftAllRight(4).AsUint8x16().And(v18).Or(v157.AsUint16x8().ShiftAllRight(6).AsUint8x16().And(v21).AsUint16x8().ShiftAllLeft(4).AsUint8x16()).Sub(v24)
					v239 := v164.AsInt8x16().ExtendLo8ToInt32().ConvertToFloat32().Mul(v106).Mul(archsimd.LoadFloat32x8(x[int(v85+v133):][:8]))
					v250 := v164.ConcatShiftBytesRight(v164, 8).AsInt8x16().ExtendLo8ToInt32().ConvertToFloat32().Mul(v106).Mul(archsimd.LoadFloat32x8(x[int((v85+8)+v133):][:8]))
					v251 := v239.Add(v250)
					v263 := v173.AsInt8x16().ExtendLo8ToInt32().ConvertToFloat32().Mul(v114).Mul(archsimd.LoadFloat32x8(x[int((v85+32)+v133):][:8]))
					v274 := v173.ConcatShiftBytesRight(v173, 8).AsInt8x16().ExtendLo8ToInt32().ConvertToFloat32().Mul(v114).Mul(archsimd.LoadFloat32x8(x[int((v85+40)+v133):][:8]))
					v275 := v263.Add(v274)
					v287 := v184.AsInt8x16().ExtendLo8ToInt32().ConvertToFloat32().Mul(v122).Mul(archsimd.LoadFloat32x8(x[int((v85+64)+v133):][:8]))
					v298 := v184.ConcatShiftBytesRight(v184, 8).AsInt8x16().ExtendLo8ToInt32().ConvertToFloat32().Mul(v122).Mul(archsimd.LoadFloat32x8(x[int((v85+72)+v133):][:8]))
					v299 := v287.Add(v298)
					v311 := v195.AsInt8x16().ExtendLo8ToInt32().ConvertToFloat32().Mul(v130).Mul(archsimd.LoadFloat32x8(x[int((v85+96)+v133):][:8]))
					v322 := v195.ConcatShiftBytesRight(v195, 8).AsInt8x16().ExtendLo8ToInt32().ConvertToFloat32().Mul(v130).Mul(archsimd.LoadFloat32x8(x[int((v85+104)+v133):][:8]))
					v323 := v311.Add(v322)
					v86 = v86.Add(v251)
					v88 = v88.Add(v275)
					v90 = v90.Add(v299)
					v92 = v92.Add(v323)
					v14++
				}
				v329 := v86.Add(v88)
				v330 := v90.Add(v92)
				v331 := v329.Add(v330)
				v25 = v25.Add(v331)
				v11++
			}
		}
		var v333 [8]float32
		v25.Store(v333[0:8])
		return float32(((((((v333[0] + v333[1]) + v333[2]) + v333[3]) + v333[4]) + v333[5]) + v333[6]) + v333[7])
	} else {
		var v358 [8]float32
		for v10 = 0; v10 < v7; v10++ {
			v364 := v10 * 210
			v389 := fp16_to_fp32(uint16(v4[(v364+208)]) | uint16(uint16(v4[(v364+209)])<<8))
			v11 = 0
			for v11 < 2 {
				v402 := v364 + (v11 * 64)
				v407 := (v364 + 128) + (v11 * 32)
				v412 := (v364 + 192) + (v11 * 8)
				v417 := (v10 * 0x100) + (v11 * 128)
				var v418 [8]float32
				var v419 [8]float32
				var v420 [8]float32
				var v421 [8]float32
				v14 = 0
				for v14 < 2 {
					v426 := v14
					v433 := v389 * float32(int8(v4[v412+v426]))
					v440 := v389 * float32(int8(v4[v412+v426+2]))
					v447 := v389 * float32(int8(v4[v412+v426+4]))
					v454 := v389 * float32(int8(v4[v412+v426+6]))
					v12 = 0
					for v12 < 8 {
						v461 := v14 * 16
						v462 := v461 + v12
						v468 := (v461 + 8) + v12
						v470 := v4[v407+v462]
						v473 := v4[v407+v468]
						v476 := v4[v402+v462]
						v479 := v476 & 15
						v483 := v470 & 3
						v491 := v4[v402+v468]
						v494 := v491 & 15
						v498 := v473 & 3
						v418[v12] += (((float32(int(v479|byte(uint32(v483)<<4))-32) * v433) * x[v417+v462]) + ((float32(int(v494|byte(uint32(v498)<<4))-32) * v433) * x[v417+v468]))
						v520 := v462 + 32
						v521 := v4[v402+v520]
						v524 := v521 & 15
						v528 := (uint32(v470) >> 2) & 3
						v537 := v468 + 32
						v538 := v4[v402+v537]
						v541 := v538 & 15
						v545 := (uint32(v473) >> 2) & 3
						v419[v12] += (((float32(int(v524|byte(uint32(v528<<4)))-32) * v440) * x[v417+v520]) + ((float32(int(v541|byte(uint32(v545<<4)))-32) * v440) * x[v417+v537]))
						v577 := (uint32(v470) >> 4) & 3
						v592 := (uint32(v473) >> 4) & 3
						v420[v12] += (((float32(int((uint32(v476)>>4)|uint32(v577<<4))-32) * v447) * x[v417+v462+64]) + ((float32(int((uint32(v491)>>4)|uint32(v592<<4))-32) * v447) * x[v417+v468+64]))
						v626 := (uint32(v470) >> 6) & 3
						v643 := (uint32(v473) >> 6) & 3
						v421[v12] += (((float32(int((uint32(v521)>>4)|uint32(v626<<4))-32) * v454) * x[v417+v462+96]) + ((float32(int((uint32(v538)>>4)|uint32(v643<<4))-32) * v454) * x[v417+v468+96]))
						v12++
					}
					v14++
				}
				v12 = 0
				v358[0] += ((v418[0] + v419[0]) + (v420[0] + v421[0]))
				v358[1] += ((v418[1] + v419[1]) + (v420[1] + v421[1]))
				v358[2] += ((v418[2] + v419[2]) + (v420[2] + v421[2]))
				v358[3] += ((v418[3] + v419[3]) + (v420[3] + v421[3]))
				v358[4] += ((v418[4] + v419[4]) + (v420[4] + v421[4]))
				v358[5] += ((v418[5] + v419[5]) + (v420[5] + v421[5]))
				v358[6] += ((v418[6] + v419[6]) + (v420[6] + v421[6]))
				v358[7] += ((v418[7] + v419[7]) + (v420[7] + v421[7]))
				v11++
			}
		}
		return float32(((((((v358[0] + v358[1]) + v358[2]) + v358[3]) + v358[4]) + v358[5]) + v358[6]) + v358[7])
	}
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const C2_tensor_dot_q6_k_IRCost = uint64(728)
