//go:build goexperiment.simd && amd64

// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=56dc50e28cc482a9e967636e2f3afa7e2b0bf383e89b20b0e5eba8c79e24c6ef
package simd

import "simd/archsimd"

type Block_q8_K struct {
	D  float32
	Qs [256]int8
}

func C2_tensor_gemv2_q6_k_q8_k(weight0 []byte, weight1 []byte, q8k []byte, cols int, out0 *float32, out1 *float32) {
	var v9 float32
	var v11 float32
	var v13 int
	var v14 int
	var v15 int
	var v16 int
	var v109 int32
	var v111 int32
	var v238 archsimd.Uint8x32
	var v239 archsimd.Uint8x32
	var v317 int32
	var v319 int32
	var v321 int32
	var v323 int32
	var v325 int
	var v440 int32
	var v441 int32
	var v442 int32
	var v443 int32
	var v451 int
	var v464 int
	var v468 int
	var v481 int
	var v485 int
	var v497 int
	var v501 int
	var v619 int32
	var v621 int32
	var v685 int32
	var v687 int32
	var v689 int32
	var v691 int32
	var v729 byte
	var v730 byte
	var v733 byte
	var v735 byte
	var v740 byte
	var v742 byte
	var v748 byte
	var v752 uint32
	var v757 byte
	var v761 uint32
	var v771 uint32
	var v780 uint32
	var v789 uint32
	var v798 uint32
	var v852 byte
	var v853 byte
	var v856 byte
	var v858 byte
	var v863 byte
	var v865 byte
	var v871 byte
	var v875 uint32
	var v880 byte
	var v884 uint32
	var v894 uint32
	var v903 uint32
	var v912 uint32
	var v921 uint32
	var v963 int32
	var v964 int32
	var v965 int32
	var v966 int32
	var v974 int
	var v987 int
	var v991 int
	var v1004 int
	var v1008 int
	var v1020 int
	var v1024 int
	v8 := cols / 0x100
	v9 = 0
	v11 = v9
	if archsimd.X86.AVX2() {
		v20 := archsimd.BroadcastUint8x32(byte(15))
		v23 := archsimd.BroadcastUint8x32(byte(3))
		v26 := archsimd.BroadcastInt16x16(int16(1))
		for v13 = 0; v13 < v8; v13++ {
			v31 := weight0[:]
			v33 := v13 * 210
			v36 := weight1[:]
			v41 := q8k[:]
			v43 := v13 * 0x124
			v71 := f32_from_bits(((uint32(v41[v43]) | uint32(uint32(v41[v43+1])<<8)) | uint32(uint32(v41[v43+2])<<16)) | uint32(uint32(v41[v43+3])<<24))
			v84 := v33 + 208
			v88 := v33 + 209
			v93 := fp16_to_fp32(uint16(v31[v84]) | uint16(uint16(v31[v88])<<8))
			v107 := fp16_to_fp32(uint16(v36[v84]) | uint16(uint16(v36[v88])<<8))
			v109 = 0
			v111 = v109
			v14 = 0
			for v14 < 2 {
				v121 := v33 + (v14 * 64)
				v129 := (v33 + 128) + (v14 * 32)
				v137 := (v33 + 192) + (v14 * 8)
				v170 := (v43 + 0x104) + (v14 * 16)
				v174 := archsimd.LoadUint8x32(v31[v129:][:32])
				v178 := archsimd.LoadUint8x32(v31[v121:][:32])
				v182 := v121 + 32
				v185 := archsimd.LoadUint8x32(v31[v182:][:32])
				v189 := archsimd.LoadUint8x32(v36[v129:][:32])
				v193 := archsimd.LoadUint8x32(v36[v121:][:32])
				v200 := archsimd.LoadUint8x32(v36[v182:][:32])
				v15 = 0
				for v15 < 4 {
					v213 := archsimd.LoadUint8x32(v41[int(((v43+4)+(v14*128))+(v15*32)):][:32])
					v216 := v15 * 2
					if v15 == 0 {
						v238 = v178.And(v20).Or(v174.And(v23).AsUint16x16().ShiftAllLeft(4).AsUint8x32())
						v239 = v193.And(v20).Or(v189.And(v23).AsUint16x16().ShiftAllLeft(4).AsUint8x32())
					} else {
						if v15 == 1 {
							v238 = v185.And(v20).Or(v174.AsUint16x16().ShiftAllRight(2).AsUint8x32().And(v23).AsUint16x16().ShiftAllLeft(4).AsUint8x32())
							v239 = v200.And(v20).Or(v189.AsUint16x16().ShiftAllRight(2).AsUint8x32().And(v23).AsUint16x16().ShiftAllLeft(4).AsUint8x32())
						} else {
							if v15 == 2 {
								v238 = v178.AsUint16x16().ShiftAllRight(4).AsUint8x32().And(v20).Or(v174.AsUint16x16().ShiftAllRight(4).AsUint8x32().And(v23).AsUint16x16().ShiftAllLeft(4).AsUint8x32())
								v239 = v193.AsUint16x16().ShiftAllRight(4).AsUint8x32().And(v20).Or(v189.AsUint16x16().ShiftAllRight(4).AsUint8x32().And(v23).AsUint16x16().ShiftAllLeft(4).AsUint8x32())
							} else {
								v238 = v185.AsUint16x16().ShiftAllRight(4).AsUint8x32().And(v20).Or(v174.AsUint16x16().ShiftAllRight(6).AsUint8x32().And(v23).AsUint16x16().ShiftAllLeft(4).AsUint8x32())
								v239 = v200.AsUint16x16().ShiftAllRight(4).AsUint8x32().And(v20).Or(v189.AsUint16x16().ShiftAllRight(6).AsUint8x32().And(v23).AsUint16x16().ShiftAllLeft(4).AsUint8x32())
							}
						}
					}
					var v311 [32]byte
					var v312 [32]byte
					v238.DotProductPairsSaturated(v213.AsInt8x32()).DotProductPairs(v26).AsUint8x32().Store(v311[0:32])
					v239.DotProductPairsSaturated(v213.AsInt8x32()).DotProductPairs(v26).AsUint8x32().Store(v312[0:32])
					v317 = 0
					v319 = v317
					v321 = v319
					v323 = v321
					v325 = 0
					for v325 < 4 {
						v332 := v325 * 4
						v336 := v332 + 1
						v343 := v332 + 2
						v350 := v332 + 3
						v317 += int32(((uint32(v311[v332]) | uint32(uint32(v311[v336])<<8)) | uint32(uint32(v311[v343])<<16)) | uint32(uint32(v311[v350])<<24))
						v321 += int32(((uint32(v312[v332]) | uint32(uint32(v312[v336])<<8)) | uint32(uint32(v312[v343])<<16)) | uint32(uint32(v312[v350])<<24))
						v325++
					}
					v325 = 4
					for v325 < 8 {
						v389 := v325 * 4
						v393 := v389 + 1
						v400 := v389 + 2
						v407 := v389 + 3
						v319 += int32(((uint32(v311[v389]) | uint32(uint32(v311[v393])<<8)) | uint32(uint32(v311[v400])<<16)) | uint32(uint32(v311[v407])<<24))
						v323 += int32(((uint32(v312[v389]) | uint32(uint32(v312[v393])<<8)) | uint32(uint32(v312[v400])<<16)) | uint32(uint32(v312[v407])<<24))
						v325++
					}
					if v15 == 0 {
						v440 = int32(int8(v31[v137]))
						v451 = v137 + 1
						v441 = int32(int8(v31[v451]))
						v442 = int32(int8(v36[v137]))
						v443 = int32(int8(v36[v451]))
					} else {
						if v15 == 1 {
							v464 = v137 + 2
							v440 = int32(int8(v31[v464]))
							v468 = v137 + 3
							v441 = int32(int8(v31[v468]))
							v442 = int32(int8(v36[v464]))
							v443 = int32(int8(v36[v468]))
						} else {
							if v15 == 2 {
								v481 = v137 + 4
								v440 = int32(int8(v31[v481]))
								v485 = v137 + 5
								v441 = int32(int8(v31[v485]))
								v442 = int32(int8(v36[v481]))
								v443 = int32(int8(v36[v485]))
							} else {
								v497 = v137 + 6
								v440 = int32(int8(v31[v497]))
								v501 = v137 + 7
								v441 = int32(int8(v31[v501]))
								v442 = int32(int8(v36[v497]))
								v443 = int32(int8(v36[v501]))
							}
						}
					}
					v512 := int32(32) * int32(read_i16(v41[int(v170+(v216*2)):]))
					v516 := int32(32) * int32(read_i16(v41[int(v170+((v216+1)*2)):]))
					v109 += (((v317 - v512) * v440) + ((v319 - v516) * v441))
					v111 += (((v321 - v512) * v442) + ((v323 - v516) * v443))
					v15++
				}
				v14++
			}
			v9 += (float32(v109) * (v93 * v71))
			v11 += (float32(v111) * (v107 * v71))
		}
		*out0 = v9
		*out1 = v11
		return
	}
	for v13 = 0; v13 < v8; v13++ {
		v541 := weight0[:]
		v543 := v13 * 210
		v546 := weight1[:]
		v551 := q8k[:]
		v553 := v13 * 0x124
		v581 := f32_from_bits(((uint32(v551[v553]) | uint32(uint32(v551[v553+1])<<8)) | uint32(uint32(v551[v553+2])<<16)) | uint32(uint32(v551[v553+3])<<24))
		v594 := v543 + 208
		v598 := v543 + 209
		v603 := fp16_to_fp32(uint16(v541[v594]) | uint16(uint16(v541[v598])<<8))
		v617 := fp16_to_fp32(uint16(v546[v594]) | uint16(uint16(v546[v598])<<8))
		v619 = 0
		v621 = v619
		v14 = 0
		for v14 < 2 {
			v631 := v543 + (v14 * 64)
			v639 := (v543 + 128) + (v14 * 32)
			v647 := (v543 + 192) + (v14 * 8)
			v675 := (v553 + 4) + (v14 * 128)
			v680 := (v553 + 0x104) + (v14 * 16)
			v15 = 0
			for v15 < 4 {
				v685 = 0
				v687 = v685
				v689 = v687
				v691 = v689
				v16 = 0
				for v16 < 16 {
					v702 := (v15 == 0) || (v15 == 2)
					v704 := v631 + v16
					v708 := v631 + (32 + v16)
					v709 := func() byte {
						if v702 {
							return v541[v704]
						}
						return v541[v708]
					}()
					v722 := func() byte {
						if v702 {
							return v546[v704]
						}
						return v546[v708]
					}()
					v725 := v639 + v16
					v724 := v541[v725]
					v727 := v546[v725]
					if v15 == 0 {
						v733 = v709 & 15
						v735 = v724 & 3
						v729 = v733 | byte(uint32(v735)<<4)
						v740 = v722 & 15
						v742 = v727 & 3
						v730 = v740 | byte(uint32(v742)<<4)
					} else {
						if v15 == 1 {
							v748 = v709 & 15
							v752 = (uint32(v724) >> 2) & 3
							v729 = v748 | byte(v752<<4)
							v757 = v722 & 15
							v761 = (uint32(v727) >> 2) & 3
							v730 = v757 | byte(v761<<4)
						} else {
							if v15 == 2 {
								v771 = (uint32(v724) >> 4) & 3
								v729 = byte((uint32(v709) >> 4) | (v771 << 4))
								v780 = (uint32(v727) >> 4) & 3
								v730 = byte((uint32(v722) >> 4) | (v780 << 4))
							} else {
								v789 = (uint32(v724) >> 6) & 3
								v729 = byte((uint32(v709) >> 4) | (v789 << 4))
								v798 = (uint32(v727) >> 6) & 3
								v730 = byte((uint32(v722) >> 4) | (v798 << 4))
							}
						}
					}
					v809 := int32(int8(v551[int(v675+((v15*32)+v16))]))
					v685 += (int32(v729) * v809)
					v689 += (int32(v730) * v809)
					v16++
				}
				v16 = 16
				for v16 < 32 {
					v825 := (v15 == 0) || (v15 == 2)
					v827 := v631 + v16
					v831 := v631 + (32 + v16)
					v832 := func() byte {
						if v825 {
							return v541[v827]
						}
						return v541[v831]
					}()
					v845 := func() byte {
						if v825 {
							return v546[v827]
						}
						return v546[v831]
					}()
					v848 := v639 + v16
					v847 := v541[v848]
					v850 := v546[v848]
					if v15 == 0 {
						v856 = v832 & 15
						v858 = v847 & 3
						v852 = v856 | byte(uint32(v858)<<4)
						v863 = v845 & 15
						v865 = v850 & 3
						v853 = v863 | byte(uint32(v865)<<4)
					} else {
						if v15 == 1 {
							v871 = v832 & 15
							v875 = (uint32(v847) >> 2) & 3
							v852 = v871 | byte(v875<<4)
							v880 = v845 & 15
							v884 = (uint32(v850) >> 2) & 3
							v853 = v880 | byte(v884<<4)
						} else {
							if v15 == 2 {
								v894 = (uint32(v847) >> 4) & 3
								v852 = byte((uint32(v832) >> 4) | (v894 << 4))
								v903 = (uint32(v850) >> 4) & 3
								v853 = byte((uint32(v845) >> 4) | (v903 << 4))
							} else {
								v912 = (uint32(v847) >> 6) & 3
								v852 = byte((uint32(v832) >> 4) | (v912 << 4))
								v921 = (uint32(v850) >> 6) & 3
								v853 = byte((uint32(v845) >> 4) | (v921 << 4))
							}
						}
					}
					v932 := int32(int8(v551[int(v675+((v15*32)+v16))]))
					v687 += (int32(v852) * v932)
					v691 += (int32(v853) * v932)
					v16++
				}
				v941 := v15 * 2
				if v15 == 0 {
					v963 = int32(int8(v541[v647]))
					v974 = v647 + 1
					v964 = int32(int8(v541[v974]))
					v965 = int32(int8(v546[v647]))
					v966 = int32(int8(v546[v974]))
				} else {
					if v15 == 1 {
						v987 = v647 + 2
						v963 = int32(int8(v541[v987]))
						v991 = v647 + 3
						v964 = int32(int8(v541[v991]))
						v965 = int32(int8(v546[v987]))
						v966 = int32(int8(v546[v991]))
					} else {
						if v15 == 2 {
							v1004 = v647 + 4
							v963 = int32(int8(v541[v1004]))
							v1008 = v647 + 5
							v964 = int32(int8(v541[v1008]))
							v965 = int32(int8(v546[v1004]))
							v966 = int32(int8(v546[v1008]))
						} else {
							v1020 = v647 + 6
							v963 = int32(int8(v541[v1020]))
							v1024 = v647 + 7
							v964 = int32(int8(v541[v1024]))
							v965 = int32(int8(v546[v1020]))
							v966 = int32(int8(v546[v1024]))
						}
					}
				}
				v1035 := int32(32) * int32(read_i16(v551[int(v680+(v941*2)):]))
				v1039 := int32(32) * int32(read_i16(v551[int(v680+((v941+1)*2)):]))
				v619 += (((v685 - v1035) * v963) + ((v687 - v1039) * v964))
				v621 += (((v689 - v1035) * v965) + ((v691 - v1039) * v966))
				v15++
			}
			v14++
		}
		v9 += (float32(v619) * (v603 * v581))
		v11 += (float32(v621) * (v617 * v581))
	}
	*out0 = v9
	*out1 = v11
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const C2_tensor_gemv2_q6_k_q8_k_IRCost = uint64(1151)
