//go:build !goexperiment.simd || !amd64

// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=ca75e9fed7655b67309a8191816d4d14b21fb75bb873821e2e17a0dcafd1d2dc
package simd

func __avx2() int {
	return 0
}

func read_i16(p []byte) int16 {
	return int16(uint16(p[0]) | uint16(uint16(p[1])<<8))
}

func C2_tensor_dot_q4_k_q8_k(weight []byte, q8k []byte, cols int) float32 {
	var v6 float32
	var v8 int
	var v9 int
	var v10 int
	var v11 int
	var v562 int32
	var v564 int32
	v6 = 0
	for v8 = 0; v8 < (cols / 0x100); v8++ {
		v379 := weight[:]
		v381 := v8 * 144
		v384 := q8k[:]
		v386 := v8 * 0x124
		v414 := f32_from_bits(((uint32(v384[v386]) | uint32(uint32(v384[v386+1])<<8)) | uint32(uint32(v384[v386+2])<<16)) | uint32(uint32(v384[v386+3])<<24))
		v427 := fp16_to_fp32(uint16(v379[v381]) | uint16(uint16(v379[(v381+1)])<<8))
		v428 := v427 * v414
		v441 := fp16_to_fp32(uint16(v379[(v381+2)]) | uint16(uint16(v379[(v381+3)])<<8))
		v442 := v441 * v414
		v446 := v381 + 4
		v459 := v386 + 0x104
		var v460 [8]byte
		var v461 [8]byte
		v9 = 0
		for v9 < 4 {
			v466 := v379[v446+v9]
			v469 := v466 & 63
			v460[v9] = v469
			v471 := v9 + 4
			v472 := v379[v446+v471]
			v475 := v472 & 63
			v461[v9] = v475
			v478 := v379[v446+v9+8]
			v481 := v478 & 15
			v460[v471] = v481 | byte(uint32((uint32(v466)>>6)<<4))
			v461[v471] = byte((uint32(v478) >> 4) | uint32((uint32(v472)>>6)<<4))
			v9++
		}
		v10 = 0
		for v10 < 4 {
			v514 := 2 * v10
			v532 := v514 + 1
			v553 := (v386 + 4) + (v10 * 64)
			v562 = 0
			v564 = v562
			v11 = 0
			for v11 < 32 {
				v570 := v379[int(((v381+16)+(v10*32))+v11)]
				v573 := v570 & 15
				v562 += (int32(v573) * int32(int8(v384[v553+v11])))
				v564 += (int32(uint32(v570)>>4) * int32(int8(v384[v553+32+v11])))
				v11++
			}
			v592 := 4 * v10
			v6 += (((float32(v562) * (v428 * float32(v460[v514]))) - (float32(int32(read_i16(v384[int(v459+(v592*2)):]))+int32(read_i16(v384[int(v459+((v592+1)*2)):]))) * (v442 * float32(v461[v514])))) + ((float32(v564) * (v428 * float32(v460[v532]))) - (float32(int32(read_i16(v384[int(v459+((v592+2)*2)):]))+int32(read_i16(v384[int(v459+((v592+3)*2)):]))) * (v442 * float32(v461[v532])))))
			v10++
		}
	}
	return v6
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const (
	__avx2_IRCost                  = uint64(2)
	Read_i16_IRCost                = uint64(11)
	C2_tensor_dot_q4_k_q8_k_IRCost = uint64(302)
)
