//go:build !goexperiment.simd || !amd64

// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=ac144e1109ed56dbccb0ddd158a1673afc5d99c01191406df92008e190ceb47e
package simd

func C2_tensor_attn_qk(q []float32, kbase []float32, pos int, stride int, scale float32, scores []float32, hd int) {
	var v7 int
	var v8 int
	var v101 float32
	for v7 = 0; v7 <= pos; v7++ {
		v101 = 0
		v8 = 0
		{
			_q := q[:hd]
			v8 = 0
			for v8 < hd {
				v101 += (_q[v8] * kbase[int((v7*stride)+v8)])
				v8++
			}
		}
		scores[v7] = v101 * scale
	}
}

func C2_tensor_attn_av(scores []float32, vbase []float32, pos int, stride int, out []float32, hd int) {
	var v6 int
	var v7 int
	var v178 float32
	for v7 = 0; v7 < hd; v7++ {
		v178 = 0
		v6 = 0
		for v6 <= pos {
			v178 += (scores[v6] * vbase[int((v6*stride)+v7)])
			v6++
		}
		out[v7] = v178
	}
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const (
	C2_tensor_attn_qk_IRCost = uint64(25)
	C2_tensor_attn_av_IRCost = uint64(23)
)
